const Items = [
  {
    itemId: 1,
    imageUrl: "/assets/image 13.svg",
    dpUrl: "/assets/image 13.png",
    userName: "User1",
    assetName: "Asset 1",
    category: "Category",
  },
  {
    itemId: 2,
    imageUrl: "/assets/img4.webp",
    dpUrl: "/assets/image 13.png",
    userName: "User2",
    assetName: "Asset 2",
    category: "Category",
  },
  {
    itemId: 3,
    imageUrl: "/assets/image 13.svg",
    dpUrl: "/assets/image 13.png",
    userName: "User3",
    assetName: "Asset 3",
    category: "Category",
  },
  {
    itemId: 4,
    imageUrl: "/assets/image 13.svg",
    dpUrl: "/assets/image 13.png",
    userName: "User4",
    assetName: "Asset 4",
    category: "Category",
  },
  {
    itemId: 5,
    imageUrl: "/assets/image 13.svg",
    dpUrl: "/assets/image 13.png",
    userName: "User5",
    assetName: "Asset 5",
    category: "Category",
  },
  {
    itemId: 6,
    imageUrl: "/assets/image 13.svg",
    dpUrl: "/assets/image 13.png",
    userName: "User6",
    assetName: "Asset",
    category: "Category",
  },
  {
    itemId: 7,
    imageUrl: "/assets/image 13.svg",
    dpUrl: "/assets/image 13.png",
    userName: "User7",
    assetName: "Asset 7",
    category: "Category",
  },
  {
    itemId: 8,
    imageUrl: "/assets/image 13.svg",
    dpUrl: "/assets/image 13.png",
    userName: "User8",
    assetName: "Asset 8",
    category: "Category",
  },
];
export default Items;
